/**
@provable automatic
@statistic nodes 143
@statistic branches 3
@see <a href="http://java.sun.com/docs/books/jls/third_edition/html/exceptions.html#11.3">Handling of an Exception (JLS, Sect. 11.3)</a>
@author Sebastian Wirkert (doc)

Proof example showing how exceptions are handled.  

When executing method <tt>m</tt> of <tt>MyClass</tt> an exception is thrown.
Java stops the execution of the try block abruptly and tries to find a
matching catch clause (the object thrown has to be an instanceof the declared
parameter type). If there is none, like in this example, the control is
transfered to the finally clause. 
*/

\classpath "classpath";
\javaSource "exceptions_java/";

\problem {
\<{
   int j =MyClass.m ();
 }\> j = 2

}
